[Preamble]
  title = "Maintainers"
  text = """
This file lists how the Cookbook Quality Metrics project is maintained. When making
changes to the system, this file tells you who needs to review your patch - you need at
least two maintainers to provide a :+1: on your pull request. Additionally, you need
to not receive a veto from a Lieutenant or the Project Lead.
Check out [How Chef is Maintained](https://github.com/opscode/chef-rfc/blob/master/rfc030-maintenance-policy.md#how-the-project-is-maintained)
for details on the process, how to become a maintainer, lieutenant, or the project lead.
"""

[Org]
  [Org.Components]
     title = "Components"

     [Org.Components.CookbookQuality]
        title = "Cookbook Quality Metrics"
        text = """
  Handles the [Cookbook Quality Metrics](https://github.com/chef-cookbooks/cookbook-quality-metrics)
  compontent which is used by the [Supermarket](https://github.com/chef/supermarket).
  """

        lieutenant = "nathenharvey"

        maintainers = [
          "tas50",
          "someara",
          "jtimberman",
          "smurawski",
          "thommay",
          "pburkholder",
          "adamleff",
          "sigje",
          "cperry",
          "cheeseplus",
          "andreelizondo",
          "jj",
          "mattray",
          "mattwrock",
          "nellshamrell",
          "ryancragun",
        ]

[people]
  [people.nathenharvey]
    Name = "Nathen Harvey"
    GitHub = "nathenharvey"
    IRC = "nathenharvey"
    Twitter = "nathenharvey"


  [people.tas50]
    Name = "Tim Smith"
    GitHub = "tas50"

  [people.someara]
    Name = "Sean O'Meara"
    GitHub = "someara"

  [people.jtimberman]
    Name = "Joshua Timberman"
    GitHub = "jtimberman"

  [people.smurawski]
    Name = "Steven Murawski"
    GitHub = "smurawski"

  [people.thommay]
    Name = "Thom May"
    GitHub = "thommay"
    IRC = "thom"
    Twitter = "thommay"

  [people.pburkholder]
    Name = "Peter Burkholder"
    GitHub = "pburkholder"

  [people.adamleff]
    Name = "Adam Leff"
    GitHub = "adamleff"

  [people.sigje]
    Name = "Jennifer Davis"
    GitHub = "iennae"

  [people.cperry]
    Name = "Carl Perry"

  [people.cheeseplus]
    Name = "Seth Thomas"

  [people.andreelizondo]
    Name = "Andre Elizondo"

  [people.jj]
    Name = "JJ Asghar"

  [people.mattray]
    Name = "Matt Ray"

  [people.mattwrock]
    Name = "Matt Wrock"

  [people.nellshamrell]
    Name = "Nell Shamrell"

  [people.ryancragun]
    Name = "Ryan Cragun"
